// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonInterface(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonInterface(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonInterface(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonInterface(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonInterface(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonInterface(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Hardware backend for model inference.
///
/// Platform support:
/// - [cpu]: All platforms
/// - [gpu]: All platforms (Metal on macOS, DirectX on Windows, Vulkan on Linux, OpenCL on Android)
/// - [npu]: Android only with LiteRT-LM (.litertlm models) - Qualcomm, MediaTek, Google Tensor
///
/// If selected backend is unavailable, engine falls back to GPU, then CPU.
enum PreferredBackend: Int {
  case cpu = 0
  case gpu = 1
  case npu = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct RetrievalResult: Hashable {
  var id: String
  var content: String
  var similarity: Double
  var metadata: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RetrievalResult? {
    let id = pigeonVar_list[0] as! String
    let content = pigeonVar_list[1] as! String
    let similarity = pigeonVar_list[2] as! Double
    let metadata: String? = nilOrValue(pigeonVar_list[3])

    return RetrievalResult(
      id: id,
      content: content,
      similarity: similarity,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      content,
      similarity,
      metadata,
    ]
  }
  static func == (lhs: RetrievalResult, rhs: RetrievalResult) -> Bool {
    return deepEqualsPigeonInterface(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonInterface(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VectorStoreStats: Hashable {
  var documentCount: Int64
  var vectorDimension: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VectorStoreStats? {
    let documentCount = pigeonVar_list[0] as! Int64
    let vectorDimension = pigeonVar_list[1] as! Int64

    return VectorStoreStats(
      documentCount: documentCount,
      vectorDimension: vectorDimension
    )
  }
  func toList() -> [Any?] {
    return [
      documentCount,
      vectorDimension,
    ]
  }
  static func == (lhs: VectorStoreStats, rhs: VectorStoreStats) -> Bool {
    return deepEqualsPigeonInterface(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonInterface(value: toList(), hasher: &hasher)
  }
}

/// Document with embedding for HNSW rebuild
///
/// Used by [getAllDocumentsWithEmbeddings] to return documents
/// with their vectors for in-memory index reconstruction.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DocumentWithEmbedding: Hashable {
  var id: String
  var content: String
  var embedding: [Double]
  var metadata: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DocumentWithEmbedding? {
    let id = pigeonVar_list[0] as! String
    let content = pigeonVar_list[1] as! String
    let embedding = pigeonVar_list[2] as! [Double]
    let metadata: String? = nilOrValue(pigeonVar_list[3])

    return DocumentWithEmbedding(
      id: id,
      content: content,
      embedding: embedding,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      content,
      embedding,
      metadata,
    ]
  }
  static func == (lhs: DocumentWithEmbedding, rhs: DocumentWithEmbedding) -> Bool {
    return deepEqualsPigeonInterface(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonInterface(value: toList(), hasher: &hasher)
  }
}

private class PigeonInterfacePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PreferredBackend(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return RetrievalResult.fromList(self.readValue() as! [Any?])
    case 131:
      return VectorStoreStats.fromList(self.readValue() as! [Any?])
    case 132:
      return DocumentWithEmbedding.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonInterfacePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PreferredBackend {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RetrievalResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VectorStoreStats {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DocumentWithEmbedding {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonInterfacePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonInterfacePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonInterfacePigeonCodecWriter(data: data)
  }
}

class PigeonInterfacePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonInterfacePigeonCodec(readerWriter: PigeonInterfacePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlatformService {
  func createModel(maxTokens: Int64, modelPath: String, loraRanks: [Int64]?, preferredBackend: PreferredBackend?, maxNumImages: Int64?, supportAudio: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeModel(completion: @escaping (Result<Void, Error>) -> Void)
  func createSession(temperature: Double, randomSeed: Int64, topK: Int64, topP: Double?, loraPath: String?, enableVisionModality: Bool?, enableAudioModality: Bool?, systemInstruction: String?, enableThinking: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeSession(completion: @escaping (Result<Void, Error>) -> Void)
  func sizeInTokens(prompt: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func addQueryChunk(prompt: String, completion: @escaping (Result<Void, Error>) -> Void)
  func addImage(imageBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func addAudio(audioBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func generateResponse(completion: @escaping (Result<String, Error>) -> Void)
  func generateResponseAsync(completion: @escaping (Result<Void, Error>) -> Void)
  func stopGeneration(completion: @escaping (Result<Void, Error>) -> Void)
  func createSessionForId(sessionId: Int64, temperature: Double, randomSeed: Int64, topK: Int64, topP: Double?, loraPath: String?, enableVisionModality: Bool?, enableAudioModality: Bool?, systemInstruction: String?, enableThinking: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeSessionId(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func sizeInTokensForSession(sessionId: Int64, prompt: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func addQueryChunkToSession(sessionId: Int64, prompt: String, completion: @escaping (Result<Void, Error>) -> Void)
  func addImageToSession(sessionId: Int64, imageBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func addAudioToSession(sessionId: Int64, audioBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func generateResponseForSession(sessionId: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func generateResponseAsyncForSession(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func stopGenerationForSession(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func initializeVectorStore(databasePath: String, completion: @escaping (Result<Void, Error>) -> Void)
  func addDocument(id: String, content: String, embedding: [Double], metadata: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func searchSimilar(queryEmbedding: [Double], topK: Int64, threshold: Double, completion: @escaping (Result<[RetrievalResult], Error>) -> Void)
  func getVectorStoreStats(completion: @escaping (Result<VectorStoreStats, Error>) -> Void)
  func clearVectorStore(completion: @escaping (Result<Void, Error>) -> Void)
  func closeVectorStore(completion: @escaping (Result<Void, Error>) -> Void)
  /// Get all documents with embeddings for HNSW index rebuild
  ///
  /// **Use case:**
  /// Called during initialize() to rebuild in-memory HNSW index
  /// from SQLite persistence layer.
  ///
  /// **Performance:**
  /// - Returns all documents in single call
  /// - Embeddings as `List<double>` (decoded from BLOB)
  ///
  /// Returns empty list if no documents stored.
  func getAllDocumentsWithEmbeddings(completion: @escaping (Result<[DocumentWithEmbedding], Error>) -> Void)
  /// Get documents by IDs with full content
  ///
  /// **Use case:**
  /// After HNSW returns candidate IDs, fetch full documents
  /// for final result construction.
  ///
  /// **Parameters:**
  /// - [ids]: List of document IDs to retrieve
  ///
  /// Returns only documents that exist (missing IDs are skipped).
  func getDocumentsByIds(ids: [String], completion: @escaping (Result<[RetrievalResult], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlatformServiceSetup {
  static var codec: FlutterStandardMessageCodec { PigeonInterfacePigeonCodec.shared }
  /// Sets up an instance of `PlatformService` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlatformService?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.createModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxTokensArg = args[0] as! Int64
        let modelPathArg = args[1] as! String
        let loraRanksArg: [Int64]? = nilOrValue(args[2])
        let preferredBackendArg: PreferredBackend? = nilOrValue(args[3])
        let maxNumImagesArg: Int64? = nilOrValue(args[4])
        let supportAudioArg: Bool? = nilOrValue(args[5])
        api.createModel(maxTokens: maxTokensArg, modelPath: modelPathArg, loraRanks: loraRanksArg, preferredBackend: preferredBackendArg, maxNumImages: maxNumImagesArg, supportAudio: supportAudioArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createModelChannel.setMessageHandler(nil)
    }
    let closeModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeModelChannel.setMessageHandler { _, reply in
        api.closeModel { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeModelChannel.setMessageHandler(nil)
    }
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let temperatureArg = args[0] as! Double
        let randomSeedArg = args[1] as! Int64
        let topKArg = args[2] as! Int64
        let topPArg: Double? = nilOrValue(args[3])
        let loraPathArg: String? = nilOrValue(args[4])
        let enableVisionModalityArg: Bool? = nilOrValue(args[5])
        let enableAudioModalityArg: Bool? = nilOrValue(args[6])
        let systemInstructionArg: String? = nilOrValue(args[7])
        let enableThinkingArg: Bool? = nilOrValue(args[8])
        api.createSession(temperature: temperatureArg, randomSeed: randomSeedArg, topK: topKArg, topP: topPArg, loraPath: loraPathArg, enableVisionModality: enableVisionModalityArg, enableAudioModality: enableAudioModalityArg, systemInstruction: systemInstructionArg, enableThinking: enableThinkingArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { _, reply in
        api.closeSession { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
    let sizeInTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.sizeInTokens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sizeInTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptArg = args[0] as! String
        api.sizeInTokens(prompt: promptArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sizeInTokensChannel.setMessageHandler(nil)
    }
    let addQueryChunkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addQueryChunk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addQueryChunkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptArg = args[0] as! String
        api.addQueryChunk(prompt: promptArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addQueryChunkChannel.setMessageHandler(nil)
    }
    let addImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageBytesArg = args[0] as! FlutterStandardTypedData
        api.addImage(imageBytes: imageBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addImageChannel.setMessageHandler(nil)
    }
    let addAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addAudio\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioBytesArg = args[0] as! FlutterStandardTypedData
        api.addAudio(audioBytes: audioBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAudioChannel.setMessageHandler(nil)
    }
    let generateResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseChannel.setMessageHandler { _, reply in
        api.generateResponse { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseChannel.setMessageHandler(nil)
    }
    let generateResponseAsyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseAsync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseAsyncChannel.setMessageHandler { _, reply in
        api.generateResponseAsync { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseAsyncChannel.setMessageHandler(nil)
    }
    let stopGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.stopGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopGenerationChannel.setMessageHandler { _, reply in
        api.stopGeneration { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopGenerationChannel.setMessageHandler(nil)
    }
    let createSessionForIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.createSessionForId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionForIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let temperatureArg = args[1] as! Double
        let randomSeedArg = args[2] as! Int64
        let topKArg = args[3] as! Int64
        let topPArg: Double? = nilOrValue(args[4])
        let loraPathArg: String? = nilOrValue(args[5])
        let enableVisionModalityArg: Bool? = nilOrValue(args[6])
        let enableAudioModalityArg: Bool? = nilOrValue(args[7])
        let systemInstructionArg: String? = nilOrValue(args[8])
        let enableThinkingArg: Bool? = nilOrValue(args[9])
        api.createSessionForId(sessionId: sessionIdArg, temperature: temperatureArg, randomSeed: randomSeedArg, topK: topKArg, topP: topPArg, loraPath: loraPathArg, enableVisionModality: enableVisionModalityArg, enableAudioModality: enableAudioModalityArg, systemInstruction: systemInstructionArg, enableThinking: enableThinkingArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionForIdChannel.setMessageHandler(nil)
    }
    let closeSessionIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeSessionId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.closeSessionId(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionIdChannel.setMessageHandler(nil)
    }
    let sizeInTokensForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.sizeInTokensForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sizeInTokensForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let promptArg = args[1] as! String
        api.sizeInTokensForSession(sessionId: sessionIdArg, prompt: promptArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sizeInTokensForSessionChannel.setMessageHandler(nil)
    }
    let addQueryChunkToSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addQueryChunkToSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addQueryChunkToSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let promptArg = args[1] as! String
        api.addQueryChunkToSession(sessionId: sessionIdArg, prompt: promptArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addQueryChunkToSessionChannel.setMessageHandler(nil)
    }
    let addImageToSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addImageToSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addImageToSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let imageBytesArg = args[1] as! FlutterStandardTypedData
        api.addImageToSession(sessionId: sessionIdArg, imageBytes: imageBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addImageToSessionChannel.setMessageHandler(nil)
    }
    let addAudioToSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addAudioToSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAudioToSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let audioBytesArg = args[1] as! FlutterStandardTypedData
        api.addAudioToSession(sessionId: sessionIdArg, audioBytes: audioBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAudioToSessionChannel.setMessageHandler(nil)
    }
    let generateResponseForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.generateResponseForSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseForSessionChannel.setMessageHandler(nil)
    }
    let generateResponseAsyncForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseAsyncForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseAsyncForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.generateResponseAsyncForSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseAsyncForSessionChannel.setMessageHandler(nil)
    }
    let stopGenerationForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.stopGenerationForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopGenerationForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.stopGenerationForSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopGenerationForSessionChannel.setMessageHandler(nil)
    }
    let initializeVectorStoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.initializeVectorStore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeVectorStoreChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let databasePathArg = args[0] as! String
        api.initializeVectorStore(databasePath: databasePathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeVectorStoreChannel.setMessageHandler(nil)
    }
    let addDocumentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addDocument\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addDocumentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let contentArg = args[1] as! String
        let embeddingArg = args[2] as! [Double]
        let metadataArg: String? = nilOrValue(args[3])
        api.addDocument(id: idArg, content: contentArg, embedding: embeddingArg, metadata: metadataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addDocumentChannel.setMessageHandler(nil)
    }
    let searchSimilarChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.searchSimilar\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchSimilarChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryEmbeddingArg = args[0] as! [Double]
        let topKArg = args[1] as! Int64
        let thresholdArg = args[2] as! Double
        api.searchSimilar(queryEmbedding: queryEmbeddingArg, topK: topKArg, threshold: thresholdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      searchSimilarChannel.setMessageHandler(nil)
    }
    let getVectorStoreStatsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.getVectorStoreStats\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVectorStoreStatsChannel.setMessageHandler { _, reply in
        api.getVectorStoreStats { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getVectorStoreStatsChannel.setMessageHandler(nil)
    }
    let clearVectorStoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.clearVectorStore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearVectorStoreChannel.setMessageHandler { _, reply in
        api.clearVectorStore { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearVectorStoreChannel.setMessageHandler(nil)
    }
    let closeVectorStoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeVectorStore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeVectorStoreChannel.setMessageHandler { _, reply in
        api.closeVectorStore { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeVectorStoreChannel.setMessageHandler(nil)
    }
    /// Get all documents with embeddings for HNSW index rebuild
    ///
    /// **Use case:**
    /// Called during initialize() to rebuild in-memory HNSW index
    /// from SQLite persistence layer.
    ///
    /// **Performance:**
    /// - Returns all documents in single call
    /// - Embeddings as `List<double>` (decoded from BLOB)
    ///
    /// Returns empty list if no documents stored.
    let getAllDocumentsWithEmbeddingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.getAllDocumentsWithEmbeddings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllDocumentsWithEmbeddingsChannel.setMessageHandler { _, reply in
        api.getAllDocumentsWithEmbeddings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAllDocumentsWithEmbeddingsChannel.setMessageHandler(nil)
    }
    /// Get documents by IDs with full content
    ///
    /// **Use case:**
    /// After HNSW returns candidate IDs, fetch full documents
    /// for final result construction.
    ///
    /// **Parameters:**
    /// - [ids]: List of document IDs to retrieve
    ///
    /// Returns only documents that exist (missing IDs are skipped).
    let getDocumentsByIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.getDocumentsByIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDocumentsByIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idsArg = args[0] as! [String]
        api.getDocumentsByIds(ids: idsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDocumentsByIdsChannel.setMessageHandler(nil)
    }
  }
}
