/// Shared platform value types for flutter_gemma.
///
/// These are plain Dart value types — the public contract that engine and RAG
/// packages depend on. They were previously generated by pigeon, but core has
/// no `@HostApi`/`@FlutterApi` (the only native bridge, `PlatformService`, lives
/// in flutter_gemma_mediapipe), so pigeon's channel codec was dead weight. Hand
/// authoring them keeps `dart:io`-free, drops the pigeon dev-dependency, and
/// removes the unused `_PigeonCodec` the analyzer flagged.
library;

/// Hardware backend for model inference.
///
/// Platform support:
/// - [cpu]: All platforms
/// - [gpu]: All platforms (Metal on macOS, DirectX on Windows, Vulkan on Linux,
///   OpenCL on Android)
/// - [npu]: With LiteRT-LM (.litertlm models) — Android (Qualcomm, MediaTek,
///   Google Tensor) and Windows (Intel LunarLake/PantherLake)
///
/// If the selected backend is unavailable, the engine falls back to GPU, then
/// CPU.
enum PreferredBackend {
  cpu,
  gpu,
  npu, // Android (Qualcomm/MediaTek/Tensor) + Windows (Intel LunarLake/PantherLake)
}

/// A single retrieval hit from a vector store query.
class RetrievalResult {
  RetrievalResult({
    required this.id,
    required this.content,
    required this.similarity,
    this.metadata,
  });

  final String id;
  final String content;
  final double similarity;
  final String? metadata;
}

/// Summary statistics for a vector store.
class VectorStoreStats {
  VectorStoreStats({
    required this.documentCount,
    required this.vectorDimension,
  });

  final int documentCount;
  final int vectorDimension;
}

/// Document with its embedding, used to rebuild an in-memory HNSW index.
///
/// Returned by `getAllDocumentsWithEmbeddings` so the index can be
/// reconstructed from persisted vectors.
class DocumentWithEmbedding {
  DocumentWithEmbedding({
    required this.id,
    required this.content,
    required this.embedding,
    this.metadata,
  });

  final String id;
  final String content;
  final List<double> embedding;
  final String? metadata;
}
