/// Shared platform value types for flutter_gemma.
///
/// These are plain Dart value types — the public contract that engine and RAG
/// packages depend on. They were previously generated by pigeon, but core has
/// no `@HostApi`/`@FlutterApi` (the only native bridge, `PlatformService`, lives
/// in flutter_gemma_mediapipe), so pigeon's channel codec was dead weight. Hand
/// authoring them keeps `dart:io`-free, drops the pigeon dev-dependency, and
/// removes the unused `_PigeonCodec` the analyzer flagged.
library;

import 'package:meta/meta.dart' show immutable;

/// Hardware backend for model inference.
///
/// Platform support:
/// - [cpu]: All platforms
/// - [gpu]: All platforms (Metal on macOS, DirectX on Windows, Vulkan on Linux,
///   OpenCL on Android)
/// - [npu]: With LiteRT-LM (.litertlm models) — Android (Qualcomm, MediaTek,
///   Google Tensor) and Windows (Intel LunarLake/PantherLake)
///
/// If the selected backend is unavailable, the engine falls back to GPU, then
/// CPU.
enum PreferredBackend {
  cpu,
  gpu,
  npu, // Android (Qualcomm/MediaTek/Tensor) + Windows (Intel LunarLake/PantherLake)
}

/// A single retrieval hit from a vector store query.
@immutable
class RetrievalResult {
  const RetrievalResult({
    required this.id,
    required this.content,
    required this.similarity,
    this.metadata,
  });

  final String id;
  final String content;
  final double similarity;
  final String? metadata;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetrievalResult &&
          other.id == id &&
          other.content == content &&
          other.similarity == similarity &&
          other.metadata == metadata;

  @override
  int get hashCode => Object.hash(id, content, similarity, metadata);

  @override
  String toString() =>
      'RetrievalResult(id: $id, similarity: $similarity, metadata: $metadata)';
}

/// Summary statistics for a vector store.
@immutable
class VectorStoreStats {
  const VectorStoreStats({
    required this.documentCount,
    required this.vectorDimension,
  });

  final int documentCount;
  final int vectorDimension;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VectorStoreStats &&
          other.documentCount == documentCount &&
          other.vectorDimension == vectorDimension;

  @override
  int get hashCode => Object.hash(documentCount, vectorDimension);

  @override
  String toString() =>
      'VectorStoreStats(documentCount: $documentCount, vectorDimension: $vectorDimension)';
}

/// Document with its embedding, used to rebuild an in-memory HNSW index.
///
/// Returned by `getAllDocumentsWithEmbeddings` so the index can be
/// reconstructed from persisted vectors.
@immutable
class DocumentWithEmbedding {
  DocumentWithEmbedding({
    required this.id,
    required this.content,
    required List<double> embedding,
    this.metadata,
  }) : embedding = List<double>.unmodifiable(embedding);

  final String id;
  final String content;
  final List<double> embedding;
  final String? metadata;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentWithEmbedding &&
          other.id == id &&
          other.content == content &&
          other.metadata == metadata &&
          _listEquals(other.embedding, embedding);

  @override
  int get hashCode =>
      Object.hash(id, content, metadata, Object.hashAll(embedding));

  @override
  String toString() =>
      'DocumentWithEmbedding(id: $id, embedding: ${embedding.length} dims, metadata: $metadata)';
}

bool _listEquals(List<double> a, List<double> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
