# Site Configuration
titleBase: flutter_gemma
favicon: favicon.ico

# Social / project links
social:
  - name: GitHub
    url: https://github.com/DenisovAV/flutter_gemma
  - name: pub.dev
    url: https://pub.dev/packages/flutter_gemma
  - name: Ko-fi
    url: https://ko-fi.com/flutter_gemma
