// Compile every API reference in the shipped agent skills against the real
// packages.
//
// Skills under packages/flutter_gemma/skills/ are read by a coding agent that
// then writes code from them. A wrong name there does not look wrong — it turns
// into confident, broken code in someone else's app. So the skills are checked
// by the only thing that actually knows what the API is: the compiler.
//
// The previous gate grepped for each name anywhere in packages/*/lib and was
// green on four APIs that do not exist: `ModelType.gemma3` matched a model URL,
// `limit:` an unrelated named argument, `spec:` a parameter name elsewhere, and
// `isThinking` a doc comment. A text search cannot tell "this name exists" from
// "this code is right". Compilation can.
//
// What is compiled:
//   - every ```dart fence, each as its own async function body. Imports written
//     in any fence of a skill are hoisted to that skill's file, so a snippet
//     using a satellite class must show the import that provides it — which is
//     the thing an agent needs to know anyway.
//   - every inline `TypeName` in the prose, as a typed declaration.
//   - every inline `TypeName.member`, as an expression. An instance member
//     referenced this way reports `static_access_to_instance_member`, which the
//     analyzer only emits when the member EXISTS — so that code counts as found.
//
// Snippets may use the placeholder inputs declared in [_placeholders] without
// declaring them. That list is inputs only — data a real app would already
// have. An API name is never a placeholder; adding one to silence an error is
// exactly the false green this script exists to prevent.
//
// What it cannot check: a symbol that still exists but changed meaning, and
// bare lower-case names mentioned only in prose. For those, read the skill —
// tool/skills_review.sh says which ones a release put in doubt.
//
// Run from the repo root:
//   dart tool/check_skills.dart
// Exit 0: everything compiles. Exit 1: a skill references something that does
// not compile. Exit 2: nothing was checked, which is not a pass.

import 'dart:io';

const _skillsDir = 'packages/flutter_gemma/skills';

/// Where the generated files are analysed. The example app depends on every
/// package in the workspace, so any import a skill shows can resolve there.
const _hostPackage = 'packages/flutter_gemma/example';

const _preamble = '''
// GENERATED by tool/check_skills.dart — deleted after each run. Do not edit.
// ignore_for_file: type=lint, unused_import, unused_local_variable, unused_element, dead_code, unused_catch_clause, dead_code_on_catch_subtype
import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter_gemma/flutter_gemma.dart';
''';

/// Inputs a snippet may use without declaring them. Data and already-built
/// objects only — never an API name.
const _placeholders = '''
late String url;
late String prompt;
late String question;
late String chunk;
late String repo;
late String path;
late Uint8List bytes;
late Uint8List pcm;
late Uint8List pcm16kMono;
late Uint8List germanPcm;
late Uint8List frenchPcm;
late InferenceModel model;
late InferenceModelSession session;
late InferenceChat chat;
late EmbeddingModel embedder;
late SpeechRecognizer recognizer;
late SpeechSynthesizer synth;
late List<Tool> myTools;
Future<Map<String, dynamic>> runTool(String name, Map<String, dynamic> args) async => {};
''';

class _Origin {
  _Origin(this.skill, this.line, this.what);
  final String skill;
  final int line;
  final String what;
}

Future<void> main() async {
  final skillsDir = Directory(_skillsDir);
  if (!skillsDir.existsSync()) {
    stderr.writeln('no skills at $_skillsDir — run from the repo root');
    exit(2);
  }

  final skills =
      skillsDir
          .listSync()
          .whereType<Directory>()
          .where((d) => File('${d.path}/SKILL.md').existsSync())
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  final work = Directory('$_hostPackage/tool/_skills_check_$pid');
  work.createSync(recursive: true);

  // generated file path -> (generated line -> where it came from)
  final origins = <String, Map<int, _Origin>>{};
  var blocks = 0;
  var inlineRefs = 0;

  try {
    for (final dir in skills) {
      final skill = dir.uri.pathSegments.where((s) => s.isNotEmpty).last;
      final src = File('${dir.path}/SKILL.md').readAsLinesSync();

      final imports = <String>{};
      final fences = <List<(int, String)>>[];
      final inline = <(int, String)>{};

      var inFence = false;
      var lang = '';
      List<(int, String)>? current;
      for (var i = 0; i < src.length; i++) {
        final line = src[i];
        final fence = RegExp(r'^```(\w*)\s*$').firstMatch(line);
        if (fence != null) {
          if (!inFence) {
            inFence = true;
            lang = fence.group(1)!;
            current = lang == 'dart' ? <(int, String)>[] : null;
          } else {
            inFence = false;
            if (current != null) fences.add(current);
            current = null;
          }
          continue;
        }
        if (inFence) {
          if (current == null) continue;
          if (RegExp(r"^\s*import\s+'").hasMatch(line)) {
            imports.add(line.trim());
          } else {
            current.add((i + 1, line));
          }
          continue;
        }
        // Prose: inline `Type` and `Type.member` references.
        for (final m in RegExp(
          r'`([A-Z][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)`',
        ).allMatches(line)) {
          inline.add((i + 1, m.group(1)!));
        }
      }

      final out = StringBuffer(_preamble);
      for (final imp in imports) {
        out.writeln(imp);
      }
      out.writeln();
      out.write(_placeholders);
      out.writeln();

      final map = <int, _Origin>{};
      var genLine = out.toString().split('\n').length;

      void emit(String code, [_Origin? origin]) {
        out.writeln(code);
        if (origin != null) map[genLine] = origin;
        genLine++;
      }

      for (var b = 0; b < fences.length; b++) {
        blocks++;
        emit('Future<void> _block$b() async {');
        for (final (n, code) in fences[b]) {
          emit(code, _Origin(skill, n, 'code block'));
        }
        emit('}');
      }

      emit('void _inline() {');
      var r = 0;
      for (final (n, ref) in inline) {
        inlineRefs++;
        final origin = _Origin(skill, n, '`$ref`');
        if (ref.contains('.')) {
          emit('  $ref;', origin);
        } else {
          emit('  $ref? _r${r++};', origin);
        }
      }
      emit('}');

      final file = File('${work.path}/${skill.replaceAll('-', '_')}.dart');
      file.writeAsStringSync(out.toString());
      origins[file.absolute.path] = map;
    }

    if (blocks == 0 && inlineRefs == 0) {
      stderr.writeln(
        'extracted nothing to check — the checker is broken, not the skills',
      );
      exit(2);
    }

    final result = await Process.run('dart', [
      'analyze',
      '--format=machine',
      work.absolute.path,
    ], workingDirectory: _hostPackage);

    final problems = <String>[];
    for (final row in '${result.stdout}\n${result.stderr}'.split('\n')) {
      final cols = row.split('|');
      if (cols.length < 8 || cols[0] != 'ERROR') continue;
      final code = cols[2].toLowerCase();
      // Only emitted when the member exists: an instance member named in prose
      // as `Type.member`. Found, not missing.
      if (code == 'static_access_to_instance_member') continue;
      final origin = origins[cols[3]]?[int.parse(cols[4])];
      final where = origin == null
          ? '${cols[3]}:${cols[4]}'
          : '${origin.skill}/SKILL.md:${origin.line}  (${origin.what})';
      problems.add('  $where\n      ${cols.sublist(7).join('|')}');
    }

    for (final p in problems) {
      stdout.writeln(p);
    }
    stdout.writeln(
      'compiled $blocks code block(s) and $inlineRefs inline reference(s) '
      'across ${skills.length} skill(s): ${problems.length} error(s)',
    );
    exitCode = problems.isEmpty ? 0 : 1;
  } finally {
    work.deleteSync(recursive: true);
  }
}
