// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Hardware backend for model inference.
///
/// Platform support:
/// - [cpu]: All platforms
/// - [gpu]: All platforms (Metal on macOS, DirectX on Windows, Vulkan on Linux, OpenCL on Android)
/// - [npu]: Android only with LiteRT-LM (.litertlm models) - Qualcomm, MediaTek, Google Tensor
///
/// If selected backend is unavailable, engine falls back to GPU, then CPU.
enum PreferredBackend {
  cpu,
  gpu,
  npu,
}

class RetrievalResult {
  RetrievalResult({
    required this.id,
    required this.content,
    required this.similarity,
    this.metadata,
  });

  String id;

  String content;

  double similarity;

  String? metadata;

  List<Object?> _toList() {
    return <Object?>[
      id,
      content,
      similarity,
      metadata,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RetrievalResult decode(Object result) {
    result as List<Object?>;
    return RetrievalResult(
      id: result[0]! as String,
      content: result[1]! as String,
      similarity: result[2]! as double,
      metadata: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RetrievalResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(content, other.content) &&
        _deepEquals(similarity, other.similarity) &&
        _deepEquals(metadata, other.metadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class VectorStoreStats {
  VectorStoreStats({
    required this.documentCount,
    required this.vectorDimension,
  });

  int documentCount;

  int vectorDimension;

  List<Object?> _toList() {
    return <Object?>[
      documentCount,
      vectorDimension,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VectorStoreStats decode(Object result) {
    result as List<Object?>;
    return VectorStoreStats(
      documentCount: result[0]! as int,
      vectorDimension: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VectorStoreStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(documentCount, other.documentCount) &&
        _deepEquals(vectorDimension, other.vectorDimension);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Document with embedding for HNSW rebuild
///
/// Used by [getAllDocumentsWithEmbeddings] to return documents
/// with their vectors for in-memory index reconstruction.
class DocumentWithEmbedding {
  DocumentWithEmbedding({
    required this.id,
    required this.content,
    required this.embedding,
    this.metadata,
  });

  String id;

  String content;

  List<double> embedding;

  String? metadata;

  List<Object?> _toList() {
    return <Object?>[
      id,
      content,
      embedding,
      metadata,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DocumentWithEmbedding decode(Object result) {
    result as List<Object?>;
    return DocumentWithEmbedding(
      id: result[0]! as String,
      content: result[1]! as String,
      embedding: (result[2]! as List<Object?>).cast<double>(),
      metadata: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DocumentWithEmbedding || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(content, other.content) &&
        _deepEquals(embedding, other.embedding) &&
        _deepEquals(metadata, other.metadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PreferredBackend) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is RetrievalResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is VectorStoreStats) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is DocumentWithEmbedding) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PreferredBackend.values[value];
      case 130:
        return RetrievalResult.decode(readValue(buffer)!);
      case 131:
        return VectorStoreStats.decode(readValue(buffer)!);
      case 132:
        return DocumentWithEmbedding.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
