// Talker decode step + first-frame codebook-0 (cb0) golden gate for
// `Qwen3TtsCore.runDecode`.
//
// This is the correctness milestone for the whole talker path: prefill ->
// decode -> KV threading -> logit split -> cb0 scoring must reproduce the
// PyTorch reference's frame-0 cb0 exactly. `qwen3_prefill_test.dart` only
// asserted `runPrefill`'s KV tensors are finite/non-empty (shape-only); this
// test is the first genuine token-for-token gate against
// `gen_qwen3_goldens.py`'s committed fixtures (`test/golden/qwen3/
// frames.json`, `frame0.json`), themselves generated by a verbatim copy of
// `Qwen3TtsPipeline.synthesize` (`text_to_speech_lm/python/
// qwen3_tts_pipeline.py`) run against the SAME model snapshot.
//
// ⚠️ Loads `talker_fp32.tflite`, NOT the int4 runtime artifact
// (`talker_int4.tflite`, `Qwen3TtsCore.load`'s default `talkerFileName`):
// the golden fixtures were generated with `talker_file='talker_fp32.tflite'`
// (see `tool/qwen3/gen_qwen3_goldens.py`'s `main()`) — int4 quantization is
// NOT bit-exact vs the PyTorch reference, so only the fp32 talker can
// reproduce the golden frame-0 cb0. fp32 is ~1.8 GB; compiling it is slow,
// hence the generous `Timeout` below.
//
// The model bundle (~1.5 GB talker_int4 + ~1.8 GB talker_fp32 + mtp/codec
// graphs + tables) is NOT committed to the repo — see
// `qwen3_prefill_test.dart`'s file header for the same skip-when-absent
// rationale ([_defaultModelDir]/`QWEN3_MODEL_DIR`).
@Tags(['qwen3-artifacts'])
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_gemma/core/domain/platform_types.dart'
    show PreferredBackend;
import 'package:flutter_gemma_speech/src/qwen3/npy_reader.dart';
import 'package:flutter_gemma_speech/src/qwen3/qwen2_bpe_encoder.dart';
import 'package:flutter_gemma_speech/src/qwen3/qwen3_prompt.dart';
import 'package:flutter_gemma_speech/src/qwen3/qwen3_sampler.dart';
import 'package:flutter_gemma_speech/src/qwen3/qwen3_tables.dart';
import 'package:flutter_gemma_speech/src/qwen3/qwen3_tts_core.dart';
import 'package:flutter_test/flutter_test.dart';

/// Default location of the Qwen3-TTS model snapshot dir — the local
/// HuggingFace cache path for `litert-community/Qwen3-TTS-12Hz-0.6B-Base`.
/// Override with the `QWEN3_MODEL_DIR` environment variable to run against
/// a different snapshot. Mirrors `qwen3_prefill_test.dart`'s identical
/// helper.
String _defaultModelDir() {
  final home = Platform.environment['HOME'] ?? '';
  return '$home/.cache/huggingface/hub/'
      'models--litert-community--Qwen3-TTS-12Hz-0.6B-Base/snapshots/'
      '66855540b3b34679f06c3ff07859603fc9514c66';
}

String _modelDir() =>
    Platform.environment['QWEN3_MODEL_DIR'] ?? _defaultModelDir();

/// Recursively scans [dir] and returns a basename -> absolute-path map for
/// every regular file found. Mirrors `qwen3_prefill_test.dart`'s identical
/// helper — every basename (incl. `talker_fp32.tflite`, sitting alongside
/// `talker_int4.tflite` in the snapshot dir) is unique across the tree.
Map<String, String> _scanArtifactPaths(String dir) {
  final out = <String, String>{};
  for (final entity in Directory(dir).listSync(recursive: true)) {
    if (entity is File) {
      out[entity.uri.pathSegments.last] = entity.path;
    }
  }
  return out;
}

void main() {
  final modelDir = _modelDir();

  test('Qwen3TtsCore.runDecode: frame-0 cb0 matches the PyTorch golden '
      '(frames.json[0][0] == frame0.json.cb0 == 1342)', () async {
    if (!Directory(modelDir).existsSync()) {
      markTestSkipped(
        'Qwen3-TTS model snapshot not found at $modelDir — set '
        'QWEN3_MODEL_DIR or fetch the model snapshot to run this test.',
      );
      return;
    }

    final artifactPaths = _scanArtifactPaths(modelDir);
    if (!artifactPaths.containsKey('talker_fp32.tflite')) {
      markTestSkipped(
        'talker_fp32.tflite not found under $modelDir — the golden '
        'fixtures were generated against the fp32 talker (int4 is not '
        'bit-exact vs the PyTorch reference) and this test needs it '
        'present to run.',
      );
      return;
    }

    // Golden fixtures — committed, always present (no skip-guard needed
    // for these reads).
    final framesGolden =
        jsonDecode(
              File('test/golden/qwen3/frames.json').readAsStringSync(),
            )['frames']
            as List;
    final firstFrame = (framesGolden[0] as List).cast<int>();
    final expectedCb0 = firstFrame[0];
    final frame0Golden =
        jsonDecode(File('test/golden/qwen3/frame0.json').readAsStringSync())
            as Map<String, dynamic>;
    // Sanity-check the fixtures agree with each other before trusting
    // either as the gate value (both are read from the same synthesize
    // run in `gen_qwen3_goldens.py`, so a mismatch here would mean a
    // fixture-generation bug, not a Dart port bug).
    expect(
      expectedCb0,
      frame0Golden['cb0'],
      reason: 'golden fixtures disagree: frames.json[0][0] vs frame0.json.cb0',
    );

    final core = await Qwen3TtsCore.load(
      artifactPaths: artifactPaths,
      backend: PreferredBackend.cpu,
      talkerFileName: 'talker_fp32.tflite',
    );
    try {
      final tablesDir = '$modelDir/tables';
      final encoder = await Qwen2BpeEncoder.fromTokenizerJson(
        artifactPaths['tokenizer.json']!,
      );
      final tables = await Qwen3Tables.load(
        codecEmbPath: '$tablesDir/codec_embedding_fp32.npy',
        mtpEmbPath: '$tablesDir/mtp_embeddings_fp16.npy',
        textEmbPath: '$tablesDir/text_embedding_fp16.npy',
        projectionNpzPath: '$tablesDir/text_projection_fp32.npz',
      );
      try {
        // Same text/template `gen_qwen3_goldens.py` used to generate the
        // fixtures (`meta.json.text` / `ids.json.template`) — the real
        // encode -> build chain, not a re-load of `ids.json` directly.
        final speaker = readNpyF32(artifactPaths['demo_speaker.npy']!);
        const text = 'Hello from on device text to speech.';
        final ids = encoder.encode(
          '<|im_start|>assistant\n$text<|im_end|>\n<|im_start|>assistant\n',
        );
        final prompt = Qwen3Prompt.build(
          ids: ids,
          speaker: speaker,
          language: 'english',
          tables: tables,
        );

        // _run_prefill (qwen3_tts_pipeline.py:315-328).
        final kv = core.runPrefill(prompt.prefill, prompt.promptLen);

        // Initial decode step: embed = prefill[0, -1] (the last prompt
        // row), pos = promptLen - 1 (recipe :219-220).
        final promptLen = prompt.promptLen;
        final pos = promptLen - 1;
        final embed = Float32List.sublistView(
          prompt.prefill,
          pos * 1024,
          promptLen * 1024,
        );

        final (cb0Logits, hidden, _) = core.runDecode(kv, embed, pos);
        expect(cb0Logits.length, 3072);
        expect(hidden.length, 1024);

        // cb0 scoring: `applyCb0Scoring` mutates in place (see its doc),
        // so pass a COPY of the raw decode logits, not the original —
        // carried forward from Task 1.5's sampler contract.
        final scores = Float32List.fromList(cb0Logits);
        applyCb0Scoring(
          scores,
          suppress: buildSuppress(),
          // Frame 0: no prior codebook-0 picks yet, so the repetition
          // penalty (which only touches indices in `history`) is a
          // no-op — matches `gen_qwen3_goldens.py`'s `history = set()`
          // at the start of its decode loop.
          history: <int>{},
          repetitionPenalty: 1.05,
          // `len(frames) < 2` is true for frame 0 (0 < 2) — forces
          // EOS's score to -1e9 so the talker cannot end the utterance
          // before at least 2 frames are produced.
          minNewTokensGuard: true,
        );
        final cb0 = pickGreedy(scores);

        // ignore: avoid_print
        print(
          'QWEN3-DECODE-TEST<<<promptLen=$promptLen pos=$pos cb0=$cb0 '
          'expectedCb0=$expectedCb0>>>',
        );

        // THE gate: reproduces the PyTorch reference's frame-0 cb0
        // exactly.
        expect(cb0, expectedCb0);
        expect(cb0, 1342);
      } finally {
        tables.dispose();
      }
    } finally {
      core.dispose();
    }
  }, timeout: const Timeout(Duration(minutes: 15)));
}
