// End-to-end `synthesize` golden gate for `Qwen3TtsCore` — the culmination
// test for the whole Qwen3-TTS port: text in, waveform out, driving the
// REAL talker + MTP + codec graphs through the host-orchestrated AR loop
// (`Qwen3TtsCore.synthesize`, ported verbatim from
// `Qwen3TtsPipeline.synthesize`, `qwen3_tts_pipeline.py:173-266`).
//
// Every prior Qwen3 test isolated one stage of the pipeline against a
// golden fixture generated by feeding that stage's REAL inputs straight
// from `frames.json`/`frame0.json` (`qwen3_talker_decode_test.dart`'s
// frame-0 cb0, `qwen3_mtp_test.dart`'s frame-0 residual,
// `qwen3_codec_test.dart`'s full-frames-to-waveform). This test instead
// drives the whole loop itself, end to end, starting only from `text` +
// `speaker` — if any stage's host-side glue (prompt assembly, cb0 scoring,
// the MTP inner loop's sampling-vs-greedy branch, the next-embed
// accumulation over all 15 MTP groups, trailing/pad indexing) is subtly
// wrong, THIS is the test that catches it, because a per-stage bug
// compounds across 26 autoregressive frames instead of being isolated to
// one golden input.
//
// ⚠️ Loads `talker_fp32.tflite`, NOT the int4 runtime artifact — same
// rationale as `qwen3_talker_decode_test.dart`'s file header: the golden
// fixtures were generated with `talker_file='talker_fp32.tflite'` (int4
// quantization is not bit-exact vs the PyTorch reference), and this run is
// greedy (`doSample: false`) so it is fully deterministic against them.
//
// PRIMARY gate: waveform Pearson correlation vs `waveform_f32.bin` (the
// PyTorch reference's decoded audio for the SAME text/speaker/greedy run) —
// robust to a single early argmax tie or 1-ULP host/XNNPACK rounding
// difference cascading through the AR loop, which can flip one token yet
// leave the audio perceptually (and numerically, via the codec's smoothing)
// identical. SECONDARY (diagnostic, not a hard requirement beyond its own
// generous threshold): the FRACTION of generated codec frames (each
// `[cb0, ...15 residuals]`) that exactly match `frames.json`'s reference
// frames — deliberately not an all-or-nothing check, for the same
// cascading-tie reason.
//
// The model bundle (~1.5 GB talker_int4 + ~1.8 GB talker_fp32 + mtp/codec
// graphs + tables) is NOT committed to the repo — see
// `qwen3_prefill_test.dart`'s file header for the same skip-when-absent
// rationale ([_defaultModelDir]/`QWEN3_MODEL_DIR`).
@Tags(['qwen3-artifacts'])
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_gemma/core/domain/platform_types.dart'
    show PreferredBackend;
import 'package:flutter_gemma_speech/src/qwen3/npy_reader.dart';
import 'package:flutter_gemma_speech/src/qwen3/qwen3_tts_core.dart';
import 'package:flutter_test/flutter_test.dart';

/// Default location of the Qwen3-TTS model snapshot dir — the local
/// HuggingFace cache path for `litert-community/Qwen3-TTS-12Hz-0.6B-Base`.
/// Override with the `QWEN3_MODEL_DIR` environment variable to run against
/// a different snapshot. Mirrors `qwen3_talker_decode_test.dart`'s identical
/// helper.
String _defaultModelDir() {
  final home = Platform.environment['HOME'] ?? '';
  return '$home/.cache/huggingface/hub/'
      'models--litert-community--Qwen3-TTS-12Hz-0.6B-Base/snapshots/'
      '66855540b3b34679f06c3ff07859603fc9514c66';
}

String _modelDir() =>
    Platform.environment['QWEN3_MODEL_DIR'] ?? _defaultModelDir();

/// Recursively scans [dir] and returns a basename -> absolute-path map for
/// every regular file found. Mirrors `qwen3_talker_decode_test.dart`'s
/// identical helper.
Map<String, String> _scanArtifactPaths(String dir) {
  final out = <String, String>{};
  for (final entity in Directory(dir).listSync(recursive: true)) {
    if (entity is File) {
      out[entity.uri.pathSegments.last] = entity.path;
    }
  }
  return out;
}

/// Reads a raw little-endian float32 PCM dump (no header, as written by
/// `numpy.ndarray.tofile`) into a [Float32List]. Mirrors
/// `qwen3_codec_test.dart`'s identical helper (see its doc for the
/// buffer-alignment rationale).
Float32List _readRawF32(String path) {
  final bytes = File(path).readAsBytesSync();
  return Float32List.view(Uint8List.fromList(bytes).buffer);
}

/// Pearson correlation coefficient between [a] and [b] (equal length).
/// Mirrors `qwen3_codec_test.dart`'s identical helper.
double _pearsonCorr(Float32List a, Float32List b) {
  final n = a.length;
  var sumA = 0.0, sumB = 0.0;
  for (var i = 0; i < n; i++) {
    sumA += a[i];
    sumB += b[i];
  }
  final meanA = sumA / n, meanB = sumB / n;
  var numerator = 0.0, denomA = 0.0, denomB = 0.0;
  for (var i = 0; i < n; i++) {
    final da = a[i] - meanA, db = b[i] - meanB;
    numerator += da * db;
    denomA += da * da;
    denomB += db * db;
  }
  return numerator / math.sqrt(denomA * denomB);
}

/// Fraction of [expected]'s rows that [actual] reproduces exactly, indexed
/// position-by-position over `min(actual.length, expected.length)` and
/// divided by `expected.length` — NOT an all-or-nothing check (see this
/// file's header): a frame produced after the two sequences have already
/// diverged is simply not a match, rather than failing the whole assertion.
/// A shorter [actual] (e.g. an early EOS pick) is penalized by the missing
/// rows counting as non-matches; a longer [actual] is not penalized further
/// (the denominator stays [expected]'s length).
double _frameAgreementFraction(List<List<int>> actual, List<dynamic> expected) {
  if (expected.isEmpty) return 1.0;
  final n = math.min(actual.length, expected.length);
  var matches = 0;
  for (var t = 0; t < n; t++) {
    final expectedRow = (expected[t] as List).cast<int>();
    final actualRow = actual[t];
    if (actualRow.length != expectedRow.length) continue;
    var rowMatches = true;
    for (var k = 0; k < expectedRow.length; k++) {
      if (actualRow[k] != expectedRow[k]) {
        rowMatches = false;
        break;
      }
    }
    if (rowMatches) matches++;
  }
  return matches / expected.length;
}

/// Index of the first frame where [actual] and [expected] disagree, or -1
/// if every compared frame matches. Diagnostic only — logged, not asserted
/// on, per this file's header (frame agreement is a fraction, not a gate).
int _firstDivergentFrame(List<List<int>> actual, List<dynamic> expected) {
  final n = math.min(actual.length, expected.length);
  for (var t = 0; t < n; t++) {
    final expectedRow = (expected[t] as List).cast<int>();
    final actualRow = actual[t];
    if (actualRow.length != expectedRow.length) return t;
    for (var k = 0; k < expectedRow.length; k++) {
      if (actualRow[k] != expectedRow[k]) return t;
    }
  }
  return -1;
}

void main() {
  final modelDir = _modelDir();

  test('Qwen3TtsCore.synthesize: greedy fp32 end-to-end matches the '
      'PyTorch-derived golden (waveform corr > 0.999)', () async {
    if (!Directory(modelDir).existsSync()) {
      markTestSkipped(
        'Qwen3-TTS model snapshot not found at $modelDir — set '
        'QWEN3_MODEL_DIR or fetch the model snapshot to run this test.',
      );
      return;
    }

    final artifactPaths = _scanArtifactPaths(modelDir);
    if (!artifactPaths.containsKey('talker_fp32.tflite')) {
      markTestSkipped(
        'talker_fp32.tflite not found under $modelDir — the golden '
        'fixtures were generated against the fp32 talker (int4 is not '
        'bit-exact vs the PyTorch reference) and this test needs it '
        'present to run.',
      );
      return;
    }

    // Golden fixtures — committed, always present (no skip-guard needed).
    final meta =
        jsonDecode(File('test/golden/qwen3/meta.json').readAsStringSync())
            as Map<String, dynamic>;
    final text = meta['text'] as String;
    final speaker = readNpyF32('test/golden/qwen3/voices/demo_speaker.npy');
    expect(speaker.length, 1024);

    final refFrames =
        (jsonDecode(
              File('test/golden/qwen3/frames.json').readAsStringSync(),
            )['frames']
            as List);
    final refWav = _readRawF32('test/golden/qwen3/waveform_f32.bin');
    expect(refFrames.length, meta['num_frames']);
    expect(refWav.length, refFrames.length * 1920);

    final core = await Qwen3TtsCore.load(
      artifactPaths: artifactPaths,
      backend: PreferredBackend.cpu,
      talkerFileName: 'talker_fp32.tflite',
    );
    try {
      final started = DateTime.now();
      final wav = core.synthesize(
        text,
        speaker: speaker,
        language: meta['language'] as String,
        doSample: false, // Golden gate: greedy, deterministic.
      );
      final elapsed = DateTime.now().difference(started);

      final corr = _pearsonCorr(wav, refWav);
      final agreement = _frameAgreementFraction(core.lastFrames, refFrames);
      final firstDivergent = _firstDivergentFrame(core.lastFrames, refFrames);

      // ignore: avoid_print
      print(
        'QWEN3-SYNTHESIZE-TEST<<<text="$text" wavLen=${wav.length} '
        'refWavLen=${refWav.length} corr=$corr '
        'frames=${core.lastFrames.length} refFrames=${refFrames.length} '
        'agreement=$agreement firstDivergentFrame=$firstDivergent '
        'elapsedMs=${elapsed.inMilliseconds}>>>',
      );

      // PRIMARY gate: waveform correlation — see this file's header for
      // why this (not exact frame equality) is the real gate.
      expect(wav.length, closeTo(refWav.length, 1920)); // +/- one frame.
      expect(corr, greaterThan(0.999));

      // SECONDARY: frame agreement as a fraction, logged above regardless
      // of outcome so a divergence is visible without re-running.
      expect(agreement, greaterThan(0.98));
    } finally {
      core.dispose();
    }
  }, timeout: const Timeout(Duration(minutes: 30)));
}
