// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.flutterberlin.flutter_gemma_builtin_ai

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonInterfacePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Availability of the OS built-in model. Wire order is frozen — append only. */
enum class AvailabilityStatus(val raw: Int) {
  AVAILABLE(0),
  DOWNLOADABLE(1),
  DOWNLOADING(2),
  UNAVAILABLE_DEVICE_UNSUPPORTED(3),
  UNAVAILABLE_OS_TOO_OLD(4),
  UNAVAILABLE_DISABLED(5),
  UNAVAILABLE_OTHER(6);

  companion object {
    fun ofRaw(raw: Int): AvailabilityStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class PigeonInterfacePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AvailabilityStatus.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AvailabilityStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BuiltInAiService {
  fun checkAvailability(callback: (Result<AvailabilityStatus>) -> Unit)
  /**
   * Starts the OS feature download (AICore). Progress arrives on the event
   * channel as {code: DOWNLOAD_PROGRESS, bytesDownloaded, bytesTotal}.
   * No-op on darwin (returns immediately; readiness is user-controlled).
   */
  fun downloadFeature(callback: (Result<Unit>) -> Unit)
  fun createModel(supportImage: Boolean, callback: (Result<Unit>) -> Unit)
  fun closeModel(callback: (Result<Unit>) -> Unit)
  fun createSession(sessionId: Long, temperature: Double, topK: Long, topP: Double?, maxOutputTokens: Long?, systemInstruction: String?, callback: (Result<Unit>) -> Unit)
  fun closeSession(sessionId: Long, callback: (Result<Unit>) -> Unit)
  fun addQueryChunk(sessionId: Long, text: String, callback: (Result<Unit>) -> Unit)
  fun addImage(sessionId: Long, imageBytes: ByteArray, callback: (Result<Unit>) -> Unit)
  fun generateResponse(sessionId: Long, callback: (Result<String>) -> Unit)
  fun generateResponseAsync(sessionId: Long, callback: (Result<Unit>) -> Unit)
  fun stopGeneration(sessionId: Long, callback: (Result<Unit>) -> Unit)
  fun countTokens(text: String, callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by BuiltInAiService. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonInterfacePigeonCodec()
    }
    /** Sets up an instance of `BuiltInAiService` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BuiltInAiService?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.checkAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkAvailability{ result: Result<AvailabilityStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.downloadFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.downloadFeature{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.createModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val supportImageArg = args[0] as Boolean
            api.createModel(supportImageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.closeModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeModel{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.createSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val temperatureArg = args[1] as Double
            val topKArg = args[2] as Long
            val topPArg = args[3] as Double?
            val maxOutputTokensArg = args[4] as Long?
            val systemInstructionArg = args[5] as String?
            api.createSession(sessionIdArg, temperatureArg, topKArg, topPArg, maxOutputTokensArg, systemInstructionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.closeSession(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.addQueryChunk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val textArg = args[1] as String
            api.addQueryChunk(sessionIdArg, textArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.addImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val imageBytesArg = args[1] as ByteArray
            api.addImage(sessionIdArg, imageBytesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.generateResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.generateResponse(sessionIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.generateResponseAsync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.generateResponseAsync(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.stopGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.stopGeneration(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma_builtin_ai.BuiltInAiService.countTokens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            api.countTokens(textArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
