name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        continue-on-error: true

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false
        continue-on-error: true

  build-example-android:
    runs-on: ubuntu-latest
    needs: analyze-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install plugin dependencies
        run: flutter pub get

      - name: Install example dependencies
        working-directory: example
        run: flutter pub get

      - name: Build example APK
        working-directory: example
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-app-debug
          path: example/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

  build-example-ios:
    runs-on: macos-latest
    needs: analyze-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install plugin dependencies
        run: flutter pub get

      - name: Install example dependencies
        working-directory: example
        run: flutter pub get

      - name: Build example iOS (no signing)
        working-directory: example
        run: flutter build ios --release --no-codesign
        continue-on-error: true
