// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPigeonInterface(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPigeonInterface(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPigeonInterface(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPigeonInterface(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPigeonInterface(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPigeonInterface(lhsKey, rhsKey) {
          if deepEqualsPigeonInterface(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPigeonInterface(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPigeonInterface(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPigeonInterface(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPigeonInterface(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPigeonInterface(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPigeonInterface(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPigeonInterface(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Hardware backend for model inference.
///
/// Platform support:
/// - [cpu]: All platforms
/// - [gpu]: All platforms (Metal on macOS, DirectX on Windows, Vulkan on Linux, OpenCL on Android)
/// - [npu]: Android only with LiteRT-LM (.litertlm models) - Qualcomm, MediaTek, Google Tensor
///
/// If selected backend is unavailable, engine falls back to GPU, then CPU.
enum PreferredBackend: Int {
  case cpu = 0
  case gpu = 1
  case npu = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct RetrievalResult: Hashable {
  var id: String
  var content: String
  var similarity: Double
  var metadata: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RetrievalResult? {
    let id = pigeonVar_list[0] as! String
    let content = pigeonVar_list[1] as! String
    let similarity = pigeonVar_list[2] as! Double
    let metadata: String? = nilOrValue(pigeonVar_list[3])

    return RetrievalResult(
      id: id,
      content: content,
      similarity: similarity,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      content,
      similarity,
      metadata,
    ]
  }
  static func == (lhs: RetrievalResult, rhs: RetrievalResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonInterface(lhs.id, rhs.id) && deepEqualsPigeonInterface(lhs.content, rhs.content) && deepEqualsPigeonInterface(lhs.similarity, rhs.similarity) && deepEqualsPigeonInterface(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RetrievalResult")
    deepHashPigeonInterface(value: id, hasher: &hasher)
    deepHashPigeonInterface(value: content, hasher: &hasher)
    deepHashPigeonInterface(value: similarity, hasher: &hasher)
    deepHashPigeonInterface(value: metadata, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VectorStoreStats: Hashable {
  var documentCount: Int64
  var vectorDimension: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VectorStoreStats? {
    let documentCount = pigeonVar_list[0] as! Int64
    let vectorDimension = pigeonVar_list[1] as! Int64

    return VectorStoreStats(
      documentCount: documentCount,
      vectorDimension: vectorDimension
    )
  }
  func toList() -> [Any?] {
    return [
      documentCount,
      vectorDimension,
    ]
  }
  static func == (lhs: VectorStoreStats, rhs: VectorStoreStats) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonInterface(lhs.documentCount, rhs.documentCount) && deepEqualsPigeonInterface(lhs.vectorDimension, rhs.vectorDimension)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VectorStoreStats")
    deepHashPigeonInterface(value: documentCount, hasher: &hasher)
    deepHashPigeonInterface(value: vectorDimension, hasher: &hasher)
  }
}

/// Document with embedding for HNSW rebuild
///
/// Used by [getAllDocumentsWithEmbeddings] to return documents
/// with their vectors for in-memory index reconstruction.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DocumentWithEmbedding: Hashable {
  var id: String
  var content: String
  var embedding: [Double]
  var metadata: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DocumentWithEmbedding? {
    let id = pigeonVar_list[0] as! String
    let content = pigeonVar_list[1] as! String
    let embedding = pigeonVar_list[2] as! [Double]
    let metadata: String? = nilOrValue(pigeonVar_list[3])

    return DocumentWithEmbedding(
      id: id,
      content: content,
      embedding: embedding,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      content,
      embedding,
      metadata,
    ]
  }
  static func == (lhs: DocumentWithEmbedding, rhs: DocumentWithEmbedding) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonInterface(lhs.id, rhs.id) && deepEqualsPigeonInterface(lhs.content, rhs.content) && deepEqualsPigeonInterface(lhs.embedding, rhs.embedding) && deepEqualsPigeonInterface(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DocumentWithEmbedding")
    deepHashPigeonInterface(value: id, hasher: &hasher)
    deepHashPigeonInterface(value: content, hasher: &hasher)
    deepHashPigeonInterface(value: embedding, hasher: &hasher)
    deepHashPigeonInterface(value: metadata, hasher: &hasher)
  }
}

private class PigeonInterfacePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PreferredBackend(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return RetrievalResult.fromList(self.readValue() as! [Any?])
    case 131:
      return VectorStoreStats.fromList(self.readValue() as! [Any?])
    case 132:
      return DocumentWithEmbedding.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonInterfacePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PreferredBackend {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RetrievalResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VectorStoreStats {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DocumentWithEmbedding {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonInterfacePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonInterfacePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonInterfacePigeonCodecWriter(data: data)
  }
}

class PigeonInterfacePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonInterfacePigeonCodec(readerWriter: PigeonInterfacePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlatformService {
  func createModel(maxTokens: Int64, modelPath: String, loraRanks: [Int64]?, preferredBackend: PreferredBackend?, maxNumImages: Int64?, supportAudio: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeModel(completion: @escaping (Result<Void, Error>) -> Void)
  func createSession(temperature: Double, randomSeed: Int64, topK: Int64, topP: Double?, loraPath: String?, enableVisionModality: Bool?, enableAudioModality: Bool?, systemInstruction: String?, enableThinking: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeSession(completion: @escaping (Result<Void, Error>) -> Void)
  func sizeInTokens(prompt: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func addQueryChunk(prompt: String, completion: @escaping (Result<Void, Error>) -> Void)
  func addImage(imageBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func addAudio(audioBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func generateResponse(completion: @escaping (Result<String, Error>) -> Void)
  func generateResponseAsync(completion: @escaping (Result<Void, Error>) -> Void)
  func stopGeneration(completion: @escaping (Result<Void, Error>) -> Void)
  func createSessionForId(sessionId: Int64, temperature: Double, randomSeed: Int64, topK: Int64, topP: Double?, loraPath: String?, enableVisionModality: Bool?, enableAudioModality: Bool?, systemInstruction: String?, enableThinking: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeSessionId(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func sizeInTokensForSession(sessionId: Int64, prompt: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func addQueryChunkToSession(sessionId: Int64, prompt: String, completion: @escaping (Result<Void, Error>) -> Void)
  func addImageToSession(sessionId: Int64, imageBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func addAudioToSession(sessionId: Int64, audioBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func generateResponseForSession(sessionId: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func generateResponseAsyncForSession(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func stopGenerationForSession(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlatformServiceSetup {
  static var codec: FlutterStandardMessageCodec { PigeonInterfacePigeonCodec.shared }
  /// Sets up an instance of `PlatformService` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlatformService?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.createModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxTokensArg = args[0] as! Int64
        let modelPathArg = args[1] as! String
        let loraRanksArg: [Int64]? = nilOrValue(args[2])
        let preferredBackendArg: PreferredBackend? = nilOrValue(args[3])
        let maxNumImagesArg: Int64? = nilOrValue(args[4])
        let supportAudioArg: Bool? = nilOrValue(args[5])
        api.createModel(maxTokens: maxTokensArg, modelPath: modelPathArg, loraRanks: loraRanksArg, preferredBackend: preferredBackendArg, maxNumImages: maxNumImagesArg, supportAudio: supportAudioArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createModelChannel.setMessageHandler(nil)
    }
    let closeModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeModelChannel.setMessageHandler { _, reply in
        api.closeModel { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeModelChannel.setMessageHandler(nil)
    }
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let temperatureArg = args[0] as! Double
        let randomSeedArg = args[1] as! Int64
        let topKArg = args[2] as! Int64
        let topPArg: Double? = nilOrValue(args[3])
        let loraPathArg: String? = nilOrValue(args[4])
        let enableVisionModalityArg: Bool? = nilOrValue(args[5])
        let enableAudioModalityArg: Bool? = nilOrValue(args[6])
        let systemInstructionArg: String? = nilOrValue(args[7])
        let enableThinkingArg: Bool? = nilOrValue(args[8])
        api.createSession(temperature: temperatureArg, randomSeed: randomSeedArg, topK: topKArg, topP: topPArg, loraPath: loraPathArg, enableVisionModality: enableVisionModalityArg, enableAudioModality: enableAudioModalityArg, systemInstruction: systemInstructionArg, enableThinking: enableThinkingArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { _, reply in
        api.closeSession { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
    let sizeInTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.sizeInTokens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sizeInTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptArg = args[0] as! String
        api.sizeInTokens(prompt: promptArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sizeInTokensChannel.setMessageHandler(nil)
    }
    let addQueryChunkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addQueryChunk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addQueryChunkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptArg = args[0] as! String
        api.addQueryChunk(prompt: promptArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addQueryChunkChannel.setMessageHandler(nil)
    }
    let addImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageBytesArg = args[0] as! FlutterStandardTypedData
        api.addImage(imageBytes: imageBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addImageChannel.setMessageHandler(nil)
    }
    let addAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addAudio\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioBytesArg = args[0] as! FlutterStandardTypedData
        api.addAudio(audioBytes: audioBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAudioChannel.setMessageHandler(nil)
    }
    let generateResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseChannel.setMessageHandler { _, reply in
        api.generateResponse { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseChannel.setMessageHandler(nil)
    }
    let generateResponseAsyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseAsync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseAsyncChannel.setMessageHandler { _, reply in
        api.generateResponseAsync { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseAsyncChannel.setMessageHandler(nil)
    }
    let stopGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.stopGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopGenerationChannel.setMessageHandler { _, reply in
        api.stopGeneration { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopGenerationChannel.setMessageHandler(nil)
    }
    let createSessionForIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.createSessionForId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionForIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let temperatureArg = args[1] as! Double
        let randomSeedArg = args[2] as! Int64
        let topKArg = args[3] as! Int64
        let topPArg: Double? = nilOrValue(args[4])
        let loraPathArg: String? = nilOrValue(args[5])
        let enableVisionModalityArg: Bool? = nilOrValue(args[6])
        let enableAudioModalityArg: Bool? = nilOrValue(args[7])
        let systemInstructionArg: String? = nilOrValue(args[8])
        let enableThinkingArg: Bool? = nilOrValue(args[9])
        api.createSessionForId(sessionId: sessionIdArg, temperature: temperatureArg, randomSeed: randomSeedArg, topK: topKArg, topP: topPArg, loraPath: loraPathArg, enableVisionModality: enableVisionModalityArg, enableAudioModality: enableAudioModalityArg, systemInstruction: systemInstructionArg, enableThinking: enableThinkingArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionForIdChannel.setMessageHandler(nil)
    }
    let closeSessionIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.closeSessionId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.closeSessionId(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionIdChannel.setMessageHandler(nil)
    }
    let sizeInTokensForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.sizeInTokensForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sizeInTokensForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let promptArg = args[1] as! String
        api.sizeInTokensForSession(sessionId: sessionIdArg, prompt: promptArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sizeInTokensForSessionChannel.setMessageHandler(nil)
    }
    let addQueryChunkToSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addQueryChunkToSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addQueryChunkToSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let promptArg = args[1] as! String
        api.addQueryChunkToSession(sessionId: sessionIdArg, prompt: promptArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addQueryChunkToSessionChannel.setMessageHandler(nil)
    }
    let addImageToSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addImageToSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addImageToSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let imageBytesArg = args[1] as! FlutterStandardTypedData
        api.addImageToSession(sessionId: sessionIdArg, imageBytes: imageBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addImageToSessionChannel.setMessageHandler(nil)
    }
    let addAudioToSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.addAudioToSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAudioToSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let audioBytesArg = args[1] as! FlutterStandardTypedData
        api.addAudioToSession(sessionId: sessionIdArg, audioBytes: audioBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAudioToSessionChannel.setMessageHandler(nil)
    }
    let generateResponseForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.generateResponseForSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseForSessionChannel.setMessageHandler(nil)
    }
    let generateResponseAsyncForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseAsyncForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseAsyncForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.generateResponseAsyncForSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseAsyncForSessionChannel.setMessageHandler(nil)
    }
    let stopGenerationForSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_gemma.PlatformService.stopGenerationForSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopGenerationForSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.stopGenerationForSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopGenerationForSessionChannel.setMessageHandler(nil)
    }
  }
}
